-- Flyway Migration: V1__init_schema.sql

-- ========================================
-- Table: category
-- ========================================
CREATE TABLE category (
    id bigint generated by default as identity primary key,
    created_at timestamp,
    updated_at timestamp,
    is_deleted BOOLEAN,
    name VARCHAR(255)
);

-- ========================================
-- Table: product
-- ========================================
CREATE TABLE product (
    id bigint generated by default as identity primary key,
    created_at timestamp,
    updated_at timestamp,
    is_deleted BOOLEAN,
    name VARCHAR(255),
    price DOUBLE PRECISION,
    description TEXT,
    category_id BIGINT,
    image_url VARCHAR(255),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

-- ========================================
-- Table: category_special_products
-- ========================================
CREATE TABLE category_special_products (
    category_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (category_id, product_id),
    CONSTRAINT fk_special_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT fk_special_product FOREIGN KEY (product_id) REFERENCES product (id)
);

-- ========================================
-- Indexes (optional but recommended)
-- ========================================
--CREATE INDEX idx_product_category_id ON product(category_id);
CREATE INDEX idx_special_category_id ON category_special_products(category_id);
CREATE INDEX idx_special_product_id ON category_special_products(product_id);

-- ========================================
-- End of schema
-- ========================================
